### ISSUE TITLE
Deprecate use of read_scopes and write_scopes

### ISSUE THREAD

**Issue by lmontrieux** [dehora/nakadi-java#228]
Use of read_scopes and write_scopes has been deprecated in Nakadi, as they are replaced by the per-event type authorization feature. We actually have a pull request to remove them entirely [1], at which point Nakadi will just ignore these two fields when they are sent as part of an event type creation or update.
This should probably be deprecated in nakadi-java as well.

[1]: https://github.com/zalando/nakadi/pull/722

**Comment by dehora** [comment]
deprecated in 0.9.7
