### ISSUE TITLE
Use none-pretty json when sending events.

### ISSUE THREAD

**Issue by v-stepanov** [dehora/nakadi-java#236]
Currently the event sending functionality sends prettified json
https://github.com/dehora/nakadi-java/blob/6630cd7520b3a4ea97ed1ca023c554c134330cb6/nakadi-java-client/src/main/java/nakadi/EventResourceReal.java#L159

Nakadi server will anyway parse the json and save it to Kafka without formatting. So it seems that there is no good reason to send prettified json to Nakadi. To minimize the traffic between Nakadi and the client it would be better to send none-pretty json to Nakadi.

Now the only options to send none-pretty json are: 
\- to provide pure strings to send method 
or 
\- to provide custom JsonSupport that will implement `toJsonBytes` without prettification.

@dehora Wdyt?

**Comment by dehora** [comment]
:+1: I can take a look. It's pretty for debugging/tracing mostly, it might be better to have flattened json by default and enable pretty if wanted.

**Comment by dehora** [comment]
Added in 0.9.5.
