### ISSUE TITLE
Stream Processor freezes after fatal error occur.

### ISSUE THREAD

**Issue by satybald** [dehora/nakadi-java#243]
Stream processor is unable to exit when fatal error occurs i.e. OutOfMemoryException. The whole JVM freezes while nakadi-java threads stay in the background doing some work.

How to simulate:
allocate 2d array `long[][] ary = new long[Integer.MAX_VALUE][Integer.MAX_VALUE];` in onNext method.

**Comment by dehora** [comment]
Addressed in 0.9.6 and up. Errors stop the processor and can be examined from the thread that started the processor
