### ISSUE TITLE
Do not use unified logger, use loggers per package

### ISSUE THREAD

**Issue by ovolynets** [dehora/nakadi-java#254]
Currently every log message is written to logger `NakadiClient` which may create confusions when configuring logging levels in the application. I suggest to log debug messages for the corresponding package (after doing #253) to simplify low-level debugging in the application.

**Comment by dehora** [comment]
Instead of the package, what about organising logs around use, eg having a separate logger for streaming, or put another way, what is it you want to be able to isolate in logs?

**Comment by dehora** [comment]
Closing, after ~5 years this hasn't been a problem in practice.
