### ISSUE TITLE
[Question] Disposing Subscriber onComplete 

### ISSUE THREAD

**Issue by satybald** [dehora/nakadi-java#255]
I'm wondering why [StreamBatchRecordSubscriber](https://github.com/dehora/nakadi-java/blob/master/nakadi-java-client/src/main/java/nakadi/StreamBatchRecordSubscriber.java#L104) is not got disposed on complete method? Might it cause to resource leak?

**Comment by dehora** [comment]
No evidence of a leak in recent versions, going to close this one.
