### ISSUE TITLE
Connection leak found in logs

### ISSUE THREAD

**Issue by olayinkasf** [dehora/nakadi-java#320]
2017-12-22 13:45:04.664  WARN 10123 --- [ ConnectionPool]
    nakadi.shadow.okhttp3.OkHttpClient       : A connection to https://nakadi-staging was leaked. 
    Did you forget to close a response body? 
    To see where this was allocated, set the OkHttpClient logger level to FINE:
    Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);

**Comment by dehora** [comment]
@olayinkasf What API calls is the code making when this happens? Some API calls return Responses that need to be closed by the caller; I'd like to distinguish between a client call that needs closing and a bug in the client where it's failing to close a resource properly.
