### ISSUE TITLE
StreamProcessor.Stop doesn't take effect

### ISSUE THREAD

**Issue by BaraaBathech** [dehora/nakadi-java#344]
While trying to stop a StreamProcessor ( in order to stop event consumption ), I got this error as "info" in the logs, and the event consumption kept working... 

```
[NakadiClient] executor service did not shutdown cleanly java.util.concurrent.Executors$FinalizableDelegatedExecutorService@319003ee
```

At that time I was using nakadi-java version: 0.9.17, but then upgraded it to 0.13.0, but that didn't help either.

Is there a way to totally shutdown a StreamProcessor?

**Comment by BaraaBathech** [comment]
We found out that we had two places in the code that start the StreamProcessors. Leaving a referenced one, and a non-referenced one. When ask to stop one, only the referenced gets stopped, while the other one keeps running in the background. We fixed that in our code.

**Comment by dehora** [comment]
@BaraaBathech thanks for following up, much appreciated. Are you happy this isn't an issue with the library or its documentation?

**Comment by BaraaBathech** [comment]
@dehora I think it is not related to the library or the documentation, it is more of how the ExecutorService coming with java is behaving.
