### ISSUE TITLE
Bintray/jcenter sunset

### ISSUE THREAD

**Issue by jjst** [dehora/nakadi-java#363]
The current installation instructions specify this library is published to Bintray. However, JFrog is sunsetting Bintray, with no new packages allowed to be uploaded as of next month (March 2021): https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

This will prevent new versions of the library from being released/published.

**Comment by jjst** [comment]
Looks like an alternative is the OSS sonatype repo. Not sure about others. https://central.sonatype.org/pages/ossrh-guide.html

**Comment by abendt** [comment]
Also Gradle is complaining if you configure a jcenter repo:


     The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0. JFrog 
     announced JCenter's sunset in February 2021. Use mavenCentral() instead. Consult the upgrading guide for further 
     information: https://docs.gradle.org/7.2/userguide/upgrading_version_6.html#jcenter_deprecation


Is there a chance to get this published to mavenCentral?

**Comment by john-coleman** [comment]
The SSL cert for jcenter.bintray.com expired today (2021-11-09).

It's back up now, the new cert is also valid from 2021-10-25 so I guess the new cert wasn't deployed fully/service bounced after getting it renewed.
